### ISSUE TITLE
missing instructions???

### ISSUE THREAD

**Issue by dominictarr** [artbrock/clutter#21]
I got to here

![image](https://user-images.githubusercontent.com/259374/165491824-9cf329df-cba0-4b28-9769-6004f9634035.png)

I got the impression that this was a p2p social network but I can't see anyone?
is there something I'm missing? I don't see any way to paste an invite code or something like that and nothing mentions connecting to a network?

**Comment by bierlingm** [comment]
Hey Dominic, thanks for trying out an early version of Clutter!

The project is not quite yet at a level of maturity where we are inviting people to seriously use it for ongoing micro-blogging, so most engagement with it is around testing it as an MVP.

Your feedback is very valuable though. What would you like to see changed/added? Or what precisely was confusing?

>>I got the impression that this was a p2p social network but I can't see anyone?<<

That's because it's pre-release. :D

>>is there something I'm missing?<<

See above.

>>I don't see any way to paste an invite code or something like that and nothing mentions connecting to a network?<<

If you've installed it, you're in it. No invite code necessary, no special connecting to a network either.

**Comment by jost-s** [comment]
No more response -> closing. Please re-open if issue persists.
